baseURL = "https://tychoindustries.cz/"
title = "TYCHO INDUSTRIES"
languageCode = "cs"
defaultContentLanguage = "cs"
paginate = "7"
theme = "spectral"

[params]
#fancyTitle = "TYCHO INDUSTRIES" # title for frontpage, may include image
fancyTitle = '<img height="200" src="/img/TI LOGO NO BG.png" alt="Logo"/>'#'<br />.'
copyright = "TYCHO INDUSTRIES s.r.o."
#startbuttonText = "KONTAKTUJTE NÁS"
startbuttonLink = "#contact"
body_is_markdown = true
#custom_css = "foo.css"
#images = "img/Logo_Try_1-1.png" #["path_to_social_image_for_link_previews.jpg"]
#bannerImage = "img/BG.png"
bannerImage= "https://www.tychoindustries.cz/img/BG.png"

[[languages.en.params.menu.main]]
url = '/en/'
title = "Home"

[[languages.en.params.menu.main]]
url = '/#contact'
title = "Contact"

[[languages.en.params.menu.main]]
url = '/'
title = "Čeština"

[[languages.cs.params.menu.main]]
url = '/'
title = "Domů"

[[languages.cs.params.menu.main]]
url = '/#contact'
title = "Kontakt"

[[languages.cs.params.menu.main]]
url = '/en/'
title = "English"

[taxonomies]
tag = "tags"
category = "categories"
series = "series"


[languages.en.params.one]
enable = true
#backgroundImage = "img/BG.png"
title = 'About Us'
body = '''
We are an industrial design workshop that can help you with the complete design and realization of your projects.
'''

[languages.cs.params.one]
enable = true
#backgroundImage = "img/BG.png"
title = 'O Nás'
body = '''
Jsme industriální designová dílna, která vám pomůže s kompletním návrhem a realizací vašich projektů.
'''

[[params.one.icon]]
icon = "fa-cube"
style = "1"
label = "CNC"

[[params.one.icon]]
icon = "fa-laptop"
style = "2"
label = "Konstrukce"

[[params.one.icon]]
icon = "fa-code"
style = "3"
label = "Code"

[languages.en.params.two]
enable = true
body_is_markdown = true
#backgroundImage = "img/BG.png"

[[languages.en.params.two.section]]
img = "img/3d design.png"
title = 'INDUSTRIAL DESIGN'
body = "- 3D product design \n- 2D drawing documentation \n- Simulations \n- Rendering and product visualization  \n- Reverse engineering"

[[languages.en.params.two.section]]
img = "img/img/3d tiskárna.png"
title = '3D PRINTING'
body = "- 3D printing of prototypes \n- 3D printing of small serie products \n- FDM, SLA, MSLA technologies \n- Printing of termoplastic and photopolymer materials"

[[languages.en.params.two.section]]
img = "img/cnc.png"
title = 'CNC MACHINING'
body = "- Turning \n- Milling"

[[languages.en.params.two.section]]
img = "img/ohýbání.png"
title = 'CNC BENDING'
body = "- Sheet metal bending (flexure) up to 15 mm thickness "

[[languages.en.params.two.section]]
img = "img/cnc laser.png"
title = 'CNC LASER'
body = "- Sheet laser cutting up to 25 mm thickness \n- Laser engraving"

[[languages.en.params.two.section]]
img = "img/cnc plazma.png"
title = 'CNC PLASMA'
body = "- Sheet plasma cutting"

[[languages.en.params.two.section]]
img = "img/povrchové úpravy.png"
title = 'SURFACE TREATMENT'
body = "- Powder coating \n- Zinc plating \n- Nickel electroplating \n- Phosphate coating \n- Chrome plating \n- Black oxide coating"

[languages.cs.params.two]
enable = true
body_is_markdown = true
#backgroundImage = "img/BG.png"

[[languages.cs.params.two.section]]
img = "img/3d design.png"
title = 'INDUSTRIÁLNÍ DESIGN'
body = "- 3D návrh produktu \n- 2D výkresová dokumentace \n- Simulace \n- Rendering a vizualice produktu \n- Reverse engineering"

[[languages.cs.params.two.section]]
img = "img/3d tiskárna.png"
title = '3D TISK'
body = "- 3D tisk prototypů \n- 3D tisk malých sérií \n- Technologie FDM, SLA, MSLA \n- Tisk termoplastů a světlocitlivých fotopolymerů"

[[languages.cs.params.two.section]]
img = "img/cnc.png"
title = 'CNC OBRÁBĚNÍ'
body = "- Soustružení \n- Frézování"

[[languages.cs.params.two.section]]
img = "img/ohýbání.png"
title = 'CNC OHÝBÁNÍ'
body = "- Ohýbání (ohraňování) do tl = 15 mm"

[[languages.cs.params.two.section]]
img = "img/cnc laser.png"
title = 'CNC LASER'
body = "- Laserové řezání plechů do tl = 25 mm \n- Laserové gravírování"

[[languages.cs.params.two.section]]
img = "img/cnc plazma.png"
title = 'CNC PLAZMA'
body = "- Plazmové řezání plechů"

[[languages.cs.params.two.section]]
img = "img/povrchové úpravy.png"
title = 'POVRCHOVÉ ÚPRAVY'
body = "- Prášková lakovna \n- Zinkování \n- Niklování \n- Fosfátování \n- Chromování \n- Černění"

[params.three]
enable = false
title = 'Tak tady fakt nevim co bude'
body = '''
Nejake chytre kecy.
'''

[[params.three.feature]]
icon = "fa-paper-plane-o"
title = "Bla?"
body = "Bla bla bla."

[[params.three.feature]]
icon = "fa-laptop"
title = "Blah blah"
body = "Bla bla bla."

[[params.three.feature]]
icon = "fa-code"
title = "Bleh"
body = "Bla bla bla."

[[params.three.feature]]
icon = "fa-headphones"
title = "Bla bla bla?"
body = "Bla bla blaBla bla blaBla bla blaBla bla bla."

[[params.three.feature]]
icon = "fa-heart-o"
title = "BLaaaaaaaaa"
body = "Bla bla bla."

[[params.three.feature]]
icon = "fa-flag-o"
title = "Nothing important"
body = "Bla bla bla."

[params.cta]
enable = false
title = "Bla"
body = "Bla bla bla."

[[params.cta.link]]
href = "#"
text = "Activate"
special = true

[[params.cta.link]]
href = "#"
text = "Learn More"
special = false

[languages.en.params.contact]
enable = true
title = "CONTACT US"
body = "Let's make something awesome together. Get in touch!"
phone = "+420 605 422 161"
#address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "info@tychoindustries.cz"
subject = "Nová Poptávka!"
formspree_form_id = "mlekzgqk"

[languages.cs.params.contact]
enable = true
#languageName = "Czech"
title = "KONTAKTUJTE NÁS"
body = "Pracujete na zajímavém projektu? Ozvětě se nám!"
phone = "+420 605 422 161"
#address = "1234 Somewhere Road<br />Some Place, Some State 0000<br />Some Country"
email = "info@tychoindustries.cz"
subject = "Nová Poptávka!"
formspree_form_id = "mlekzgqk"

[params.social]
twitter = ""
facebook = ""
instagram = ""
dribble = ""

# language specific options

[languages.en]
weight = 0
languageName = "English"
languageCode = 'en-US'
description = 'Transforming ideas into reality'
startbuttonText = "Contact Us"



[languages.cs]
weight = 10
languageName = "Czech"
languageCode = 'cs-CZ'
description = 'Měníme nápady v realitu'
startbuttonText = "KONTAKTUJTE NÁS"
